### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by j-lefevere-laoide** [baigouy/tissue_analyzer#1]
Hi,
I am trying to use Tissue Analyzer on Mac (OS 13.0).
When I try to open the GUI using the line 'python -m epyseg.ta', I get the following message: 'Illegal instruction: 4'.
Any ideas as to what could be causing this and how to solve it?
Thanks!

**Comment by baigouy** [comment]
Hi,

I really have no idea what the problem can be. Is this really the only error message you get ? Unfortunately, this does not sound like a very informative error message to me (and unfortunately I don't have a Mac OS 13 to play with) ? Did you notice an error during install ?

Really sorry... I wish I could do better...

**Comment by j-lefevere-laoide** [comment]
Hello,
Thank you for your message.
I don't seem to be able to get it to work but I will ask Mac users around me!

**Comment by baigouy** [comment]
Thanks for the info and really sorry about that...
