### ISSUE TITLE
Mapping the tracked cell in the tracked_cells_resized.tif to trackid in cells.csv in pyTA

### ISSUE THREAD

**Issue by msphan** [baigouy/tissue_analyzer#10]
Hi,

I can vizualize the tracked cells by exporting the tracked_cells_resized.tif from pyTA, but then I'm not sure how to find the corresponding track id in the cells.csv for a given tracked cell in the tracked_cells_resized.tif. Any hint here?

Many thanks!
Son

**Comment by baigouy** [comment]
Dear Son,

the track ID is an int24 value (i.e. an RGB color) where the first 8 bits contain the red color, the second and third 8bits are the blue and green components. If cells were tracked then when you export cells, there is a column 'track_id' that corresponds to this, besides this there is also a local_id that corresponds to the gray 'color' in the cells.tif file, also there are centroid (and similar) coordinates for each cell, so playing with one or all of these parameters should allow you to find where your cell is. The track ID is unique to a cell througout the movie (this is the only real tracking), the local id is unique for a single image but can change from one frame to the next and so cannot be used to identify a cell uniquely. If a cell is lost then its track ID will change (i.e. a new track ID is assigned to the cell). Hope this helps.

best,

Benoit

**Comment by msphan** [comment]
Many thanks!

**Comment by baigouy** [comment]
welcome
