### ISSUE TITLE
Advanced Segmentation and Tracking Correction Crash

### ISSUE THREAD

**Issue by oahassan99** [baigouy/tissue_analyzer#3]
Hello,
I have been using python Tissue Analyzer for Windows to do segmentation of epithelial cells and noticed that whenever I tried to run the advanced segmentation and tracking correction, the window crashes and I am given an "unhandled Python exception." Is there any way around this? Any help would be appreciated.

**Comment by oahassan99** [comment]
Edit: It seems the tracking tab had to be used along with the segmentation to use the advanced segmentation and tracking correction.

**Comment by baigouy** [comment]
You are right, @oahassan99, the tabs are ordered and the 'tracking' is mandatory for the 'advanced tracking' interface. I should probably add a warning to inform the user when he skips a step that further analysis is not going to work. I'll add this to my TODO list. Many thanks again for the bug report.
