### ISSUE TITLE
Issue with python version 2.7

### ISSUE THREAD

**Issue by TomPJWyatt** [baigouy/tissue_analyzer#4]
Hello, I'm having a problem installing tissue analyzer on a macbook (os 12.6). I'm not able to create a conda environment with python 2.7, I think due to the issue discussed here: https://stackoverflow.com/questions/67380286/anaconda-channel-for-installing-python-2-7

Is there a way to use a different python version?

Many thanks for the help and the great software!

**Comment by baigouy** [comment]
Hello @TomPJWyatt , the software doesnt support python 2.7, the install tuto specifies to use python 3.7:  'conda create -n TA python==3.7'. Hope this helps. Best. Benoit

**Comment by TomPJWyatt** [comment]
Hi Benoit, thanks for the quick response and help. Sorry I was getting my 2.7 and 3.7s mixed up! In fact I was having an osx related issue with python 3.7. This is the correct link to someone having a similar problem: https://stackoverflow.com/questions/70205633/cannot-install-python-3-7-on-osx-arm64

The advice there solved the initial problem for me but now I get a 'zsh: illegal hardware instruction' error when I try to run 'python -m epyseg.ta'

It seems to be the same issue as discussed here: https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook

I haven't tried solving with the advice given there but am happy sticking with the Fiji distribution for now. Just letting you know in case it's useful. 

Thanks again for the great software,
Tom

**Comment by baigouy** [comment]
Dear @TomPJWyatt,

Thanks for your update and sorry for the late reply. From what I understand from the stackoverflow post, python 3.7 was never packaged for this system. The main problem I have is that I don't have access to a recent mac system so I cannot test by myself and confirm what is said on stackoverflow. If I understand well the second problem it means that the default tensorflow package is somehow not correct for the system either. Maybe the fix they propose would work, but again I cannot test... I have in the meantime released a version of pyta for python 3.8, it may work, the only thing you have to change to use it is  'conda create -n TA python==3.8' but I remember that I had problems on old macs with this version for unclear reasons... But maybe the problems would be gone with more recent macs ? I have also released a preversion (never tested and therefore may have bugs) for python 3.9 that can be installed as follows (I only show the few changes compared to the default install):

conda create -n TA python==3.9
....
pip install -U -i https://test.pypi.org/simple/ epyseg==0.1.30
...

you may skip (most likely) the two lines:
'pip install -U numpy'
'pip install -U scikit-learn'

both solutions may work (or not...). But I guess if you are happy with the java version then that may be the best solution for you for now

sorry for the inconvenience,

all the best,

Benoit
