### ISSUE TITLE
TA plugin FIJI

### ISSUE THREAD

**Issue by sindhum98** [baigouy/tissue_analyzer#7]
When I try to export cell data/ export bond data from the FIJI plugin GUI, I am getting a warning box which says 'Sorry but there seems to be a problem with the DB associated to file', could you please look into this? The plugin was working fine for me last week.

**Comment by baigouy** [comment]
I suggest a restart of the computer in case the library that reads SQLite databases crashed. If the problem persists, please feel free to reopen the issue.
