### ISSUE TITLE
File opening error

### ISSUE THREAD

**Issue by uqzmann** [baigouy/tissue_analyzer#9]
I am unable to open any image files in tissue analyser plugin. I tried different image formats, also tried reinstalling the plugin. But couldn't get the image file to open. Either there is a severe lag or some other issue I cannot troubleshoot. Can someone help me with this?

**Comment by baigouy** [comment]
Are you using the python or java version ? Anyway most images should be supported. If you are using FIJI, I recommend to use a fresh download of FIJI from 'https://fiji.sc/' and it is important to download a FIJI version that is bundled with java as on many systems the default java version that ships with the system is incompatible and usually creates some image reading issues. Besides this dragging and dropping images onto the user interface is the best way to load images to the soft. Hope this helps?
